# Generated by Django 2.1.7 on 2019-02-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanny.Host')),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanny.Nanny')),
            ],
        ),
    ]
